# arxivの学問領域の指定
subject: 'cat:cs.CV'

# 検索キーワード
keywords:
        NLoS: 3
        hyperspectral: 3
        domain adaptation: 2
        passive: 1
        cosine similarity: 1

# 通知の閾値
score_threshold: 1
